<?php

use \Drupal\user\Entity\User;

/**
 * Implements hook_form_alter().
 */
function hide_revision_info_form_alter(&$form, &$form_state, $form_id) {
  if (!str_starts_with($form_id, 'node_')) {
    return;
  }

  /** @var $currentUser User */
  $currentUser = User::load(\Drupal::currentUser()->id());

  if ($currentUser && !$currentUser->hasRole('administrator')) {
    $form['revision_information']['#access'] = FALSE;
  }
}
